export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOAD_DEVICES = 'LOAD_DEVICES';
export const LOAD_DEVICE_INFO = 'LOAD_DEVICE_INFO';
export const LOAD_DEVICE_INFO_WITH_TIME = 'LOAD_DEVICE_INFO_WITH_TIME';
export const TOGGLE_DEVICE_STATUS = 'TOGGLE_DEVICE_STATUS';
export const LOADING_DEVICE_INFO = 'LOADING_DEVICE_INFO'